// Code generated by "stringer -type=SectionType"; DO NOT EDIT.

package menu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedSection-0]
	_ = x[Meal-1]
	_ = x[Category-2]
	_ = x[Container-3]
}

const _SectionType_name = "UndefinedSectionMealCategoryContainer"

var _SectionType_index = [...]uint8{0, 16, 20, 28, 37}

func (i SectionType) String() string {
	if i < 0 || i >= SectionType(len(_SectionType_index)-1) {
		return "SectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SectionType_name[_SectionType_index[i]:_SectionType_index[i+1]]
}
